# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qr.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Qr(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.qrcodeui = QtWidgets.QToolButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.qrcodeui.setFont(font)
        self.qrcodeui.setText("Quét QR")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/map/qrcode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.qrcodeui.setIcon(icon)
        self.qrcodeui.setIconSize(QtCore.QSize(250, 250))
        self.qrcodeui.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.qrcodeui.setObjectName("qrcodeui")
        self.gridLayout_2.addWidget(self.qrcodeui, 0, 0, 1, 1)
        self.cancel= QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cancel.setFont(font)
        self.cancel.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.cancel, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.cancel2 = QtWidgets.QPushButton(self.page_2)
        self.cancel2.setGeometry(QtCore.QRect(240, 20, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cancel2.setFont(font)
        self.cancel2.setObjectName("cancel2")
        self.qrimage = QtWidgets.QLabel(self.page_2)
        self.qrimage.setGeometry(QtCore.QRect(210, 140, 211, 211))
        self.qrimage.setText("")
        self.qrimage.setPixmap(QtGui.QPixmap(":/map/qrcode.png"))
        self.qrimage.setObjectName("qrimage")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.cancel2.setText(_translate("MainWindow", "Cancel"))
import map_rc
